spring:
  application:
    name: audit-service
  datasource:
    url: jdbc:postgresql://localhost:5432/docdb
    username: cdc
    password: cdc
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
  kafka:
    # 9094 = listener hote de Kafka (l'app tourne hors Docker)
    bootstrap-servers: localhost:9094
    consumer:
      group-id: audit-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8082
